apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: consumer-claim0
  name: consumer-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: consumer-claim1
  name: consumer-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi