apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ahmed/DDIA/final_project/Weather-Stations-Monitoring/base-central-station/ParquetFiles/"
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ahmed/DDIA/final_project/Weather-Stations-Monitoring/base-central-station/BitcaskFiles/"
  storageClassName: standard