apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consumer
  template:
    metadata:
      labels:
        service: consumer
    spec:
      volumes:
        - name: consumer-volume
          persistentVolumeClaim:
            claimName: consumer-claim
      containers:
        - image: central-station:latest
          imagePullPolicy: Never
          name: consumer
          volumeMounts:
            - mountPath: /tmp/ParquetFiles/
              name: consumer-volume
#            - mountPath: /tmp/BitcaskFiles/
#              name: consumer-claim1

#        - name: consumer-claim1
#          persistentVolumeClaim:
#            claimName: consumer-claim1
