apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consumer
  template:
    metadata:
      labels:
        service: consumer
    spec:
      volumes:
        - name: consumer-volume0
          persistentVolumeClaim:
            claimName: consumer-claim0
        - name: consumer-volume1
          persistentVolumeClaim:
            claimName: consumer-claim1
      containers:
        - image: central-station:latest
          imagePullPolicy: Never
          name: consumer
          volumeMounts:
            - mountPath: "/tmp/ParquetFiles/"
              name: consumer-volume0
            - mountPath: "/tmp/BitcaskFiles/"
              name: consumer-volume1

       
