apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consumer
  template:
    metadata:
      labels:
        service: consumer
    spec:
      volumes:
        - name: parquet-files-volume
          persistentVolumeClaim:
            claimName: pv0
        - name: bitcask-files-volume
          persistentVolumeClaim:
            claimName: pv1
      containers:
        - image: central-station:latest
          imagePullPolicy: Never
          name: consumer
          volumeMounts:
            - mountPath: "/tmp/ParquetFiles/"
              name: parquet-files-volume
            - mountPath: "/tmp/BitcaskFiles/"
              name: bitcask-files-volume

       
