version: '3'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  station1:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=1

  station2:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=2

  station3:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=3

  station4:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=4

  station5:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=5

  station6:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=6

  station7:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=7

  station8:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=8

  station9:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=9

  station10:
    image: 'weather-station:latest'
    depends_on:
      - kafka
    environment:
      - STATION_ID=10

  consumer:
    image: "central-station:latest"
    volumes:
      - /home/ahmed/DDIA/final_project/Weather-Stations-Monitoring/base-central-station/ParquetFiles/:/tmp/ParquetFiles/
      - /home/ahmed/DDIA/final_project/Weather-Stations-Monitoring/base-central-station/BitcaskFiles/:/tmp/BitcaskFiles/

  processors:
    image: "humidity-processor:latest"
    depends_on:
      - kafka
