apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: station10
  name: station10
spec:
  replicas: 1
  selector:
    matchLabels:
      service: station10
  strategy: {}
  template:
    metadata:
      labels:
        service: station10
    spec:
      containers:
        - env:
            - name: STATION_ID
              value: "10"
          image: weather-station:latest
          imagePullPolicy: Never
          name: station10
          resources: {}
      restartPolicy: Always
