version: '3'
networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - app-tier
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:2181
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BITNAMI_DEBUG=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  producer:
    restart: always
    image: "weather-station:latest"
    networks:
      - app-tier
    depends_on:
      - kafka
  consumer:
    restart: always
    image: "central-station:latest"
    networks:
      - app-tier
    depends_on:
      - producer

#      - KAFKA_CFG_NUM_PARTITIONS=2
#    volumes:
#       - ./kafka_data:/bitnami/kafka
